trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'MyFeed'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-B'
        goals: 'package'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/target/*.jar'
        artifactName: 'myapp'

- stage: Test
  jobs:
  - job: Test
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'myapp'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-B'
        goals: 'test'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(Build.SourcesDirectory)/target/surefire-reports/TEST-*.xml'

- stage: StaticAnalysis
  jobs:
  - job: SonarQube
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'TestSonarqubeConnection'
        scannerMode: 'CLI'
        cliProjectKey: 'myapp'
        cliProjectName: 'My App'
        cliSources: '$(Build.SourcesDirectory)'
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-B'
        goals: 'clean verify sonar:sonar'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
